before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

# Speed up build by leveraging travis caches
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

language: java

#dist: trusty

jdk:
  - openjdk8
  - openjdk11

branches:
  #Don't build tags
  except:
    - /^v\d/

#Below skips the installation step completely (https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step)
#We need it because otherwise Travis CI injects an awkward './gradlew assemble' step into the CI workflow
#We want to control and decide what Gradle tasks are executed
install:
  - true

script:
  # We are using && below on purpose
  # ciPerformRelease must run only when the entire build has completed
  # This guarantees that no release steps are executed when the build or tests fail
  - ./gradlew build idea -s  #&& ./gradlew ciPerformRelease